import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('docs/index.html','utf8');
const core=fs.readFileSync('docs/app-core-v144.js','utf8');
const comments=fs.readFileSync('docs/app-comments-v144.js','utf8');
const reader=fs.readFileSync('docs/app-reader-v144.js','utf8');
const admin=fs.readFileSync('docs/app-admin-v144.js','utf8');
const init=fs.readFileSync('docs/app-init-v144.js','utf8');
const bridge=fs.readFileSync('extension/app-bridge.js','utf8');
const manifest=JSON.parse(fs.readFileSync('extension/manifest.json','utf8'));
const build=fs.readFileSync('scripts/build-extension.mjs','utf8');
assert.match(html,/NERO Favorite Reader/);
for(const view of ['home','comments','read','return','manage'])assert.match(html,new RegExp(`data-view="${view}"`));
for(const id of ['inboxRefresh','priorityRefresh','reader','returnScan','autoToggle','backfillScan','diagnoseManage'])assert.match(html,new RegExp(`id="${id}"`));
assert.match(core,/nero-app-request/);
assert.match(core,/noteOk/);
assert.match(comments,/inbox_scan/);
assert.match(comments,/priority_scan/);
assert.match(comments,/reply_comment/);
assert.match(reader,/DOMParser/);
assert.match(reader,/favorite_add/);
assert.match(admin,/return_status/);
assert.match(admin,/auto_status/);
assert.match(init,/fullInboxScan/);
assert.match(bridge,/const VERSION = '0\.1\.44'/);
assert.match(bridge,/NERO_APP_V2/);
assert.doesNotMatch(bridge,/MutationObserver/);
assert.equal(manifest.version,'0.1.44');
const readerScript=manifest.content_scripts.find(row=>row.matches.includes('__READER_MATCH__'));
assert.deepEqual(readerScript.js,['app-bridge.js']);
for(const file of ['app-api-core.js','app-api-inbox.js','app-api-priority.js','app-api-router.js'])assert.ok(manifest.background.scripts.includes(file));
assert.ok(manifest.background.scripts.includes('return-likes-v141.js'));
assert.match(build,/cosmos-invest\.github\.io\/nero-swipe-reader/);
assert.match(build,/__READER_BASE__/);
assert.match(build,/__READER_MATCH__/);
console.log('pages-check-ok');
