import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('docs/index.html','utf8');
const app=fs.readFileSync('docs/app.js','utf8');
const build=fs.readFileSync('scripts/build-extension.mjs','utf8');
const manifest=fs.readFileSync('extension/manifest.json','utf8');
const pagesBridge=fs.readFileSync('extension/pages-bridge.js','utf8');
const articleReader=fs.readFileSync('extension/article-reader.js','utf8');
const returnLikesHelper=fs.readFileSync('extension/return-likes-v141.js','utf8');
const returnLikesUi=fs.readFileSync('extension/return-likes-ui.js','utf8');
assert.match(html,/NERO Favorite Reader/);
assert.match(html,/id="autoToggle"/);
assert.match(html,/id="backfillScan"/);
assert.match(html,/id="historyList"/);
assert.match(html,/id="returnLikesScan"/);
assert.match(html,/id="commentPriorityRefresh"/);
assert.match(html,/id="commentPriorityList"/);
assert.match(html,/id="magazine"/);
assert.match(app,/nero-search-request/);
assert.match(app,/nero-magazine-add-request/);
assert.match(app,/nero-auto-status-request/);
assert.match(app,/nero-backfill-control-request/);
assert.match(app,/nero-return-likes-control-request/);
assert.match(app,/nero-engagement-request/);
assert.match(app,/nero-creator-latest-request/);
assert.match(app,/nero-article-shown/);
assert.match(app,/COMMENT_PRIORITY_REFRESH_MS/);
assert.match(app,/renderHistory/);
assert.match(pagesBridge,/NERO_AUTO_STATUS/);
assert.match(pagesBridge,/NERO_BACKFILL_SCAN/);
assert.match(pagesBridge,/NERO_BACKFILL_START/);
assert.match(pagesBridge,/NERO_RETURN_LIKES_SCAN/);
assert.match(pagesBridge,/NERO_RETURN_LIKES_START/);
assert.match(pagesBridge,/NERO_ARTICLE_FETCH/);
assert.match(pagesBridge,/reader-rich-body/);
assert.match(pagesBridge,/DOMParser/);
assert.match(articleReader,/api\/v3\/notes/);
assert.match(articleReader,/NERO_ARTICLE_FETCH/);
assert.match(articleReader,/bodyText/);
assert.match(returnLikesHelper,/FAST_INTERVAL_MINUTES = 1/);
assert.match(returnLikesHelper,/NERO_RETURN_TARGETS_STATUS/);
assert.match(returnLikesUi,/対象記事一覧を更新/);
assert.match(returnLikesUi,/新しいスキだけ1分間隔/);
assert.match(manifest,/"version": "0\.1\.41"/);
assert.match(manifest,/"article-reader\.js"/);
assert.match(manifest,/"return-likes-v141\.js"/);
assert.match(manifest,/"return-likes-ui\.js"/);
assert.match(app,/ネロのお気に入り🌙/);
assert.match(build,/cosmos-invest\.github\.io\/nero-swipe-reader/);
assert.match(build,/__READER_BASE__/);
assert.match(build,/__READER_MATCH__/);
console.log('pages-check-ok');
